version: '3.7'

services:
  sample:
    build:
      context: .
      dockerfile: Dockerfile
    image: intulsa_backend
    container_name: ingulsa_backend
    volumes:
      - '/usr/src/inTulsa-be'
      - '/usr/src/inTulsa-be/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
