-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT,
    "city" TEXT,
    "state" TEXT,
    "resume" TEXT,
    "phone" TEXT,
    "linkedin" TEXT,
    "skills" TEXT,
    "expertise" TEXT,
    "experienceYears" TEXT,
    "workspace" TEXT,
    "aboutUs" TEXT,
    "referredBy" TEXT,
    "roles" TEXT,
    "externalId" TEXT,
    "gender" TEXT,
    "address1" TEXT,
    "address2" TEXT,
    "zip" TEXT,
    "description" TEXT,
    "status" TEXT,
    "seniority" TEXT,
    "username" TEXT,
    "logo" TEXT,
    "companyName" TEXT,
    "annualRevenue" TEXT,
    "companyURL" TEXT,
    "numEmployees" TEXT,
    "revenue" TEXT,
    "dateFounded" TIMESTAMP(3),
    "employeeType" TEXT,
    "experience" TEXT,
    "hourlyRate" TEXT,
    "willRelocate" TEXT,
    "ethnicity" TEXT,
    "workAuthorized" TEXT,
    "disability" TEXT,
    "avatar" TEXT,
    "occupation" TEXT,
    "employmentPreference" TEXT,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
