export type Company = {
    id: number;
    Address_Address?: string;
    Address_Address2?: string;
    Address_City?: string;
    Address_countryCode?: string;
    Address_Country?: string;
    Address_countryName?: string;
    Address_State?: string;
    Address_timezone?: string;
    Address_Zip?: string;
    AnnualRevenueMillions?: string;
    BillingAddress_BillingAddress?: string;
    BillingAddress_Address2?: string;
    BillingAddress_BillingCity?: string;
    BillingAddress_BillingState?: string;
    BillingAddress_BillingZip?: string;
    BillingAddress_BillingCountry?: string;
    BillingAddress_countryCode?: string;
    BillingAddress_countryName?: string;
    BillingContact?: string;
    BillingFrequency?: string;
    BillingPhone?: string;
    BranchID_id?: string;
    Industries_SectorList?: string;
    CompanyDescription?: string;
    CompanyWebsite?: string;
    Competitors?: string;
    CulturePerks?: string;
    DateEntered?: Date;
    OppStageUpdated?: Date;
    NotesLastUpdated?: Date;
    PartnerOpsLead?: string;
    AtentoLocalPortco?: string;
    OppType?: string;
    OppStage?: string;
    ReasonHoldClosed?: string;
    TILVertical?: string;
    JobsPotential?: string;
    LocalPartners?: string;
    SourcedFrom?: string;
    RelatedFund?: string;
    LocalPartner?: string;
    PrimaryContact?: string;
    Star?: string;
    CompanyClassifcation?: string;
    CompanyLegalType?: string;
    IsthisaFund?: string;
    BDOwner?: string;
    GKFF?: string;
    NewtoTulsa?: string;
};

export type Job = {
    id: number,
    address_address1?: string,
    address_address2?: string,
    address_city?: string,
    address_state?: string,
    address_zip?: string,
    address_country_id?: number,
    benefits?: string,
    billRateCategoryID?: number,
    bonusPackage?: string,
    certificationList?: string,
    clientBillRate?: number,
    clientContact?: number,
    clientCorporationID?: number,
    date_added?: Date,
    date_closed?: Date,
    date_end?: Date,
    date_last_exported?: Date,
    date_last_modified?: Date,
    date_last_published?: Date,
    degreeList?: string,
    description?: string,
    durationWeeks?: number,
    educationDegree?: string,
    employmentType?: string,
    externalID?: string,
    feeArrangement?: number,
    hoursOfOperation?: string,
    hoursPerWeek?: number,
    interviews?: number,
    isClientEditable?: boolean,
    isDeleted?: boolean,
    isInterviewRequired?: boolean,
    isJobcastPublished?: boolean,
    isOpen?: boolean,
    isPublic?: number,
    location_address1?: string,
    location_address2?: string,
    location_city?: string,
    location_state?: string,
    location_state_id?: string,
    location_state_name?: string,
    location_zip?: string,
    location_country_id?: string,
    location_country_name?: string,
    location_country_code?: string,
    markUpPercentage?: number,
    numOpenings?: number,
    onSite?: string,
    owner?: number,
    payRate?: number,
    publicDescription?: string,
    publishedZip?: string,
    reasonClosed?: string,
    reportTo?: string,
    reportToClientContact?: number,
    salary?: number,
    salaryUnit?: string,
    skillList?: string,
    source?: string,
    startDate?: Date,
    status?: string,
    taxRate?: number,
    taxStatus?: string,
    title?: string,
    travelRequirements?: string,
    type?: number,
    willRelocate?: boolean,
    yearsRequired?: number
};

export type BullhornClientContact = {
    id: string;
    category?: string;
    certifications?: string;
    clientCorporation?: string;
    comments?: string;
    dateAdded?: string;
    dateLastModified?: string;
    dateLastVisit?: string;
    description?: string;
    desiredCategories?: string;
    desiredSkills?: string;
    desiredSpecialties?: string;
    division?: string;
    email?: string;
    email2?: string;
    email3?: string;
    externalID?: string;
    fax?: string;
    fax2?: string;
    fax3?: string;
    firstName?: string;
    isAnonymized?: string;
    isDayLightSavings?: string;
    isDeleted?: string;
    lastName?: string;
    leads?: string;
    middleName?: string;
    mobile?: string;
    name?: string;
    namePrefix?: string;
    nameSuffix?: string;
    nickName?: string;
    numEmployees?: string;
    occupation?: string;
    office?: string;
    owner?: string;
    pager?: string;
    password?: string;
    phone?: string;
    phone2?: string;
    phone3?: string;
    preferredContact?: string;
    skills?: string;
    source?: string;
};