export type Company = {
    id: string,
    address_address1?: string,
    address_address2?: string,
    address_city?: string,
    address_state?: string,
    address_zip?: string,
    annualRevenue?: string,
    billingAddress_address1?: string,
    billingAddress_address2?: string,
    billingAddress_city?: string,
    billingAddress_state?: string,
    billingAddress_zip?: string,
    billingContact?: string,
    billingFrequency?: string,
    billingPhone?: string,
    businessSectorList?: string,
    companyDescription?: string,
    companyURL?: string,
    competitors?: string,
    culture?: string,
    customDate1_3?: string,
    customFloat1_3?: string,
    customInt1_3?: string,
    customText1_20?: string,
    customTextBlock1_5?: string,
    dateFounded?: string,
    dateLastModified?: string,
    externalID?: string,
    feeArrangement?: string,
    funding?: string,
    industryList?: string,
    invoiceFormat?: string,
    name?: string,
    notes?: string,
    numEmployees?: string,
    numOffices?: string,
    ownerShip?: string,
    phone?: string,
    revenue?: string,
    status?: string,
    taxRate?: string,
    tickerSymbol?: string,
    workWeekStart?: string,
    address_country_id?: string,
    datedAdded?: string,
};

export type Job = {
    id: string;
    address_address1?: string;
    address_address2?: string;
    address_city?: string;
    address_state?: string;
    address_zip?: string;
    address_country_id?: string;
    benefits?: string;
    billRateCategoryID?: string;
    bonusPackage?: string;
    certificationList?: string;
    clientBillRate?: string;
    clientContact?: string;
    clientCorporationID?: string;
    date_added?: string;
    date_closed?: string;
    date_end?: string;
    date_last_exported?: string;
    date_last_modified?: string;
    date_last_published?: string;
    degreeList?: string;
    description?: string;
    durationWeeks?: string;
    educationDegree?: string;
    employmentType?: string;
    externalID?: string;
    feeArrangement?: string;
    hoursOfOperation?: string;
    hoursPerWeek?: string;
    interviews?: string;
    isClientEditable?: string;
    isDeleted?: string;
    isInterviewRequired?: string;
    isJobcastPublished?: string;
    isOpen?: string;
    isPublic?: string;
    location_address1?: string;
    location_address2?: string;
    location_city?: string;
    location_state?: string;
    location_state_id?: string;
    location_state_name?: string;
    location_zip?: string;
    location_country_id?: string;
    location_country_name?: string;
    location_country_code?: string;
    markUpPercentage?: string;
    numOpenings?: string;
    onSite?: string;
    owner?: string;
    payRate?: string;
    publicDescription?: string;
    publishedZip?: string;
    reasonClosed?: string;
    reportTo?: string;
    reportToClientContact?: string;
    salary?: string;
    salaryUnit?: string;
    skillList?: string;
    source?: string;
    startDate?: string;
    status?: string;
    taxRate?: string;
    taxStatus?: string;
    title?: string;
    travelRequirements?: string;
    type?: string;
    willRelocate?: string;
    yearsRequired?: string;
    hidden?: boolean;
};

export type ClientContact = {
    id: string;
    address_address1?: string;
    address_address2?: string;
    address_city?: string;
    address_state?: string;
    address_zip?: string;
    address_country_id?: string;
    category?: string;
    certifications?: string;
    clientCorporation?: string;
    comments?: string;
    dateAdded?: string;
    dateLastModified?: string;
    dateLastVisit?: string;
    description?: string;
    desiredCategories?: string;
    desiredSkills?: string;
    desiredSpecialties?: string;
    division?: string;
    email?: string;
    email2?: string;
    email3?: string;
    externalID?: string;
    fax?: string;
    fax2?: string;
    fax3?: string;
    firstName?: string;
    isAnonymized?: string;
    isDayLightSavings?: string;
    isDeleted?: string;
    lastName?: string;
    leads?: string;
    middleName?: string;
    mobile?: string;
    name?: string;
    namePrefix?: string;
    nameSuffix?: string;
    nickName?: string;
    numEmployees?: string;
    occupation?: string;
    office?: string;
    owner?: string;
    pager?: string;
    password?: string;
    phone?: string;
    phone2?: string;
    phone3?: string;
    preferredContact?: string;
    skills?: string;
    source?: string;
};

export type Candidate = {
    id: string;
    address_address1?: string;
    address_address2?: string;
    address_city?: string;
    address_state?: string;
    address_zip?: string;
    address_country_id?: string;
    certifications?: string;
    comments?: string;
    companyName?: string;
    companyURL?: string;
    dateAdded?: string;
    dateAvailable?: string;
    dateAvailableEnd?: string;
    dateI9Expiration?: string;
    dateLastComment?: string;
    dateLastModified?: string;
    dateNextCall?: string;
    dateOfBirth?: string;
    dayRate?: string;
    dayRateLow?: string;
    degreeList?: string;
    description?: string;
    desiredLocations?: string;
    disability?: string;
    educationDegree?: string;
    email?: string;
    email2?: string;
    email3?: string;
    employeeType?: string;
    employmentPreference?: string;
    ethnicity?: string;
    experience?: string;
    externalID?: string;
    fax?: string;
    fax2?: string;
    fax3?: string;
    firstName?: string;
    gender?: string;
    hourlyRate?: string;
    hourlyRateLow?: string;
    i9OnFile?: string;
    isAnonymized?: string;
    isDeleted?: string;
    isEditable?: string;
    isExempt?: string;
    lastName?: string;
    leads?: string;
    maritalStatus?: string;
    massMailOptOut?: string;
    middleName?: string;
    mobile?: string;
    name?: string;
    namePrefix?: string;
    nameSuffix?: string;
    nickName?: string;
    numCategories?: string;
    numOwners?: string;
    occupation?: string;
    otherDeductionsAmount?: string;
    otherIncomeAmount?: string;
    pager?: string;
    paperWorkOnFile?: string;
    password?: string;
    payrollClientStartDate?: string;
    payrollStatus?: string;
    phone?: string;
    phone2?: string;
    phone3?: string;
    preferredContact?: string;
    primarySkills?: string;
    recentClientList?: string;
    referredBy?: string;
    salary?: string;
    salaryLow?: string;
    secondarySkills?: string;
    skillSet?: string;
    smsOptIn?: string;
    source?: string;
    specialties?: string;
    ssn?: string;
    stateAddtionalWitholdingsAmount?: string;
    stateExemptions?: string;
    stateFilingStatus?: string;
    status?: string;
    taxID?: string;
    taxState?: string;
    timeZoneOffsetEST?: string;
    tobaccoUser?: string;
    totalDependentClaimAmount?: string;
    travelLimit?: string;
    travelMethod?: string;
    twoJobs?: string;
    type?: string;
    userDateAdded?: string;
    username?: string;
    veteran?: string;
    willRelocate?: string;
    workAuthorized?: string;
    workPhone?: string;
};

export type Lead = {
    id: string;
    address_address1?: string;
    address_address2?: string;
    address_city?: string;
    address_state?: string;
    address_zip?: string;
    address_country_id?: string;
    campaignSource?: string;
    candidates?: string;
    category?: string;
    clientContacts?: string;
    clientCorporation?: string;
    comments?: string;
    companyName?: string;
    companyURL?: string;
    conversionSource?: string;
    dateAdded?: string;
    dateLastComment?: string;
    dateLastModified?: string;
    dateLastVisited?: string;
    description?: string;
    division?: string;
    email?: string;
    email2?: string;
    email3?: string;
    fax?: string;
    fax2?: string;
    fax3?: string;
    firstName?: string;
    isAnonymized?: string;
    isDayLightSavingsTime?: string;
    isDeleted?: string;
    lastName?: string;
    leadSource?: string;
    massMailOptOut?: string;
    middleName?: string;
    mobile?: string;
    name?: string;
    namePrefix?: string;
    nameSuffix?: string;
    nickName?: string;
    notes?: string;
    numEmployees?: string;
    occupation?: string;
    owner?: string;
    ownerCorporation?: string;
    pager?: string;
    phone?: string;
    phone2?: string;
    phone3?: string;
    preferredContact?: string;
    primarySkills?: string;
    priority?: string;
    referredByPerson?: string;
    reportToPerson?: string;
    role?: string;
    salary?: string;
    salaryLow?: string;
    secondarySkills?: string;
    skillSet?: string;
    smsOptIn?: string;
    specialties?: string;
    status?: string;
    timeZoneOffsetEST?: string;
    type?: string;
    willRelocate?: string;
}