export const COORDINATOR = 'coordinator';
export const CANDIDATE = 'candidate';
export const COMPANY = 'company';
export const ROLES = [COORDINATOR, CANDIDATE, COMPANY];

const job_filter_exclude_keys = [
    "academic",
  "adjudication",
  "admissions",
  "admitting",
  "adult",
  "advocacy",
  "advocate",
  "aircraft",
  "alumni",
  "americorps",
  "analyzer tech",
  "anestesia",
  "animal",
  "animal control",
  "aquatics",
  "art",
  "assembler",
  "assembly technician",
  "asset",
  "athlete",
  "athletic",
  "athletics",
  "attorney",
  "auto",
  "automation technician",
  "automotive",
  "bailiff",
  "barback",
  "bartender",
  "baseball",
  "beauty",
  "behavior",
  "behavior coach",
  "bilingual",
  "billing",
  "bim",
  "bingo",
  "biologist",
  "biomed",
  "blender",
  "body repair",
  "breakfast",
  "budget",
  "builder",
  "building",
  "buyer",
  "cafeteria",
  "cage",
  "call center",
  "camp",
  "campaign",
  "cancer",
  "canvasser",
  "care",
  "care coordinator",
  "career coach",
  "career navigator",
  "carpenter",
  "case management",
  "case manager",
  "cashier",
  "casino",
  "chef",
  "chemical",
  "chemist",
  "child",
  "circulation",
  "claims",
  "class",
  "classroom",
  "cleaner",
  "clerk",
  "clinic",
  "clinical",
  "clinician",
  "club",
  "cna",
  "collection",
  "collector",
  "college",
  "compliance",
  "composition",
  "construction",
  "controller",
  "cook",
  "copywriter",
  "corporate card",
  "counsel",
  "counseling",
  "counselor",
  "count team",
  "court",
  "credit",
  "crew",
  "crew leader",
  "crime",
  "crisis",
  "crossing guard",
  "culinary",
  "custodial",
  "custodian",
  "customer pick-up",
  "defender",
  "delivery",
  "dietary",
  "dietician",
  "dinner",
  "dishwasher",
  "dispatcher",
  "distribution assistant",
  "doctor",
  "donation",
  "donation",
  "donor",
  "drainage",
  "driver",
  "drug",
  "economist",
  "economy",
  "edit",
  "editor",
  "educate",
  "education",
  "educator",
  "electrician",
  "electronics tech",
  "elementary",
  "emergency",
  "emergency response",
  "engineering tec",
  "english",
  "environment",
  "environmental",
  "equipment",
  "esl",
  "esthetician",
  "ethernet",
  "event",
  "exercise",
  "externship",
  "fabricator",
  "faculty",
  "family",
  "field coach",
  "field service",
  "financial aid",
  "financial counselor",
  "fire",
  "fleet",
  "food",
  "forensic",
  "foreperson",
  "forester",
  "forklift",
  "fraud",
  "front desk",
  "garbage",
  "garden",
  "gardener",
  "gift stocker",
  "giving",
  "goods",
  "governance",
  "grade",
  "graduate",
  "grants",
  "greenhouse",
  "gutter installer",
  "gym",
  "gymnastics",
  "health",
  "historic",
  "history",
  "home care",
  "horticulture",
  "horticulturist",
  "hospital",
  "hospitalist",
  "house manager",
  "housekeeper",
  "housekeeping",
  "housing",
  "humanities",
  "hvac",
  "i am awesome",
  "imaging",
  "impact coach",
  "inspector",
  "instructor",
  "intake",
  "intern",
  "internal controls",
  "internship",
  "intervention",
  "inventory",
  "investigator",
  "jailer",
  "janitor",
  "janitorial",
  "job coach",
  "jurisdiction",
  "justice",
  "kfaq",
  "kids",
  "kitchen",
  "kotv",
  "kqcw",
  "lab",
  "laborer",
  "lacrosse",
  "lakes",
  "landscape",
  "language",
  "languages",
  "law",
  "lcsw",
  "leak",
  "learn",
  "leasing",
  "legal",
  "liberal arts",
  "librarian",
  "library",
  "license",
  "life enrichment",
  "life science",
  "life sciences",
  "lifeguard",
  "lift operator",
  "lighting",
  "lpn",
  "lunch",
  "machine operator",
  "machinist",
  "maintenance",
  "mammographer",
  "manufacturing",
  "massage",
  "material",
  "math",
  "mechanic",
  "medical",
  "medication",
  "membership",
  "merchandiser",
  "microbiologist",
  "microbiology",
  "mlt",
  "mortgage",
  "mt",
  "musician",
  "mutual fund",
  "nail tech",
  "neighborhood",
  "newspaper",
  "nurse",
  "nursing",
  "nutrition",
  "occupancy",
  "occupational",
  "office assistant",
  "on call",
  "on-call",
  "optometrist",
  "ot",
  "painter",
  "paralegal",
  "paramedic",
  "paraprofessional",
  "park",
  "parking",
  "parks",
  "parmacist",
  "patient",
  "pavement",
  "penetration",
  "permit",
  "personal trainer",
  "pet",
  "pharmacy",
  "phlebotomist",
  "phone representative",
  "photographer",
  "photography",
  "physical",
  "physician",
  "physics",
  "plant",
  "plumber",
  "plumber",
  "police",
  "political science",
  "porter",
  "portioner",
  "pretreatment",
  "principal",
  "probation",
  "processing",
  "production",
  "production worker",
  "professor",
  "psychiatric",
  "psychiatrist",
  "psychiatry",
  "psychologist",
  "psychology",
  "public facilities",
  "public safety",
  "public works",
  "qc",
  "quality control",
  "quality coordinator",
  "quality manager",
  "ra",
  "radio",
  "radiologist",
  "radiology",
  "real estate",
  "receiving",
  "receptionist",
  "record specialist",
  "recovery",
  "recreation",
  "recycling",
  "refrigeration",
  "refrigerator",
  "refuse",
  "regulatory",
  "rehousing",
  "repair technician",
  "research",
  "residence",
  "resident",
  "resident assistant",
  "respiratory",
  "retail",
  "revenue",
  "right-of-way",
  "rn",
  "room service",
  "safety",
  "sales assistant",
  "sales associate",
  "scheduling",
  "school",
  "secretary",
  "security",
  "server",
  "service leader",
  "service worker",
  "shelver",
  "shift lead",
  "shipper",
  "shipping",
  "shoe",
  "sign language",
  "sobering",
  "soccer",
  "social services",
  "social worker",
  "sociology",
  "sonographer",
  "speech",
  "spill response",
  "staff pharmacist",
  "staffing",
  "sterile",
  "stock",
  "store",
  "storm",
  "stormwater",
  "street",
  "student",
  "study",
  "subject matter",
  "substitute",
  "success coach",
  "supply",
  "surgeon",
  "surgery",
  "surgical",
  "surplus",
  "surveillance",
  "swim",
  "switchboard",
  "table games",
  "teach",
  "teacher's aide",
  "telecommunications",
  "teller",
  "textile",
  "theater",
  "theatre",
  "therapist",
  "tier i technician",
  "tier ii technician",
  "tier iii technician",
  "title agent",
  "tooling",
  "traffic",
  "traffic systems analyst",
  "transfer",
  "transition",
  "transportation",
  "trauma",
  "troops",
  "truck driver",
  "tutor",
  "unboxer",
  "urology",
  "utilities",
  "utility",
  "vault",
  "vegetation",
  "vehicle",
  "vendor",
  "veterinarian",
  "veterinary",
  "victim",
  "volleyball",
  "volunteer",
  "warehouse",
  "wares",
  "warning",
  "water",
  "water service",
  "welder",
  "welding",
  "word processing",
  "word processor",
  "worker i",
  "worker ii",
  "write",
  "writer",
  "x-ray",
  "xray",
  "youth",
  "zoning"
];

const city_filter_include_keys = [
    "Bixby,OK",
    "Broken Arrow,OK",
    "Jenks,OK",
    "Owasso,OK",
    "Remote",
    "Sapulpa,OK",
    "Tulsa,OK"
];


export const JOB_EXCLUDE_KEYS_REGEX = new RegExp(`(${job_filter_exclude_keys.join('|')})`, 'gi');
export const CITY_INCLUDE_KEYS_REGEX = new RegExp(`(${city_filter_include_keys.join('|')})`, 'gi');